const seed = { groups:[
  {id:'carry',name:'出差 · 随身携带',description:'上飞机前确认都在身上',color:'blue',items:[['身份证 / 护照','证件夹里','packed'],['充电器和转换头','黑色收纳袋','packed'],['降噪耳机','随身小包','todo'],['洗漱包','登机箱外层','todo'],['备用眼镜','','todo']]},
  {id:'ship',name:'邮寄 · 快递包裹',description:'到达后再拆的东西',color:'peach',items:[['会议资料与样品','顺丰 · SF14203829','shipping'],['换季衣物','箱子 B-02','todo'],['咖啡器具','箱子 B-03','todo']]},
  {id:'move',name:'搬家 · 纸箱 A',description:'书籍、桌面和小物件',color:'purple',items:[['设计书籍 12 本','标记：书房','packed'],['桌面摆件','易碎 · 请向上','packed'],['数据线收纳盒','','todo']]},
  {id:'home',name:'搬家 · 纸箱 B',description:'厨房和生活用品',color:'green',items:[['马克杯和餐具','气泡膜包裹','todo'],['香薰与蜡烛','','todo']]}
 ],activity:[['已将「充电器和转换头」标记为已打包','今天 10:24'],['新增包裹追踪号 SF14203829','昨天 18:42'],['创建分组「搬家 · 纸箱 B」','昨天 17:08']]};
let state = JSON.parse(localStorage.getItem('packflow-data') || 'null') || seed; let trip = JSON.parse(localStorage.getItem('packflow-trip') || 'null') || {name:'上海出差'}; let activeFilter='all'; let activeCategory='all'; let query=''; let draggedItem=null; let draggedGroup=null;
const categories=['数码产品','服装','小电器','证件','生活用品','文件资料','书籍','家居用品','餐厨用品','其他'];
function categoryForItem(name){if(/充电器|耳机|数据线|收纳盒/.test(name))return '数码产品';if(/衣物/.test(name))return '服装';if(/咖啡器具/.test(name))return '小电器';if(/身份证|护照|眼镜/.test(name))return '证件';if(/资料|样品/.test(name))return '文件资料';if(/书籍/.test(name))return '书籍';if(/摆件/.test(name))return '家居用品';if(/马克杯|餐具/.test(name))return '餐厨用品';if(/洗漱|香薰|蜡烛/.test(name))return '生活用品';return '其他'}
function normalizeState(){state.groups.forEach(group=>{const legacyStatus=group.items.some(item=>item[2]==='received')?'received':group.items.some(item=>item[2]==='shipping')?'shipping':null;group.status=group.status||legacyStatus||'todo';group.items.forEach(item=>{if(item[2]==='shipping'||item[2]==='received')item[2]='packed';item[3]=categories.includes(item[3])?item[3]:categoryForItem(item[0])})})}
normalizeState();
const $=s=>document.querySelector(s); const save=()=>{localStorage.setItem('packflow-data',JSON.stringify(state));render()};
const preferredTheme=localStorage.getItem('packflow-theme') || (window.matchMedia('(prefers-color-scheme: dark)').matches?'dark':'light');
function applyTheme(theme){document.body.classList.toggle('dark',theme==='dark');localStorage.setItem('packflow-theme',theme);const dark=theme==='dark';$('#themeToggle').setAttribute('aria-pressed',String(dark));$('.theme-icon').textContent=dark?'☀':'☾';$('.theme-label').textContent=dark?'日间模式':'深夜模式';$('#themeColor').setAttribute('content',dark?'#182027':'#f5f7f9')}
function items(){return state.groups.flatMap(g=>g.items.map((x,i)=>({name:x[0],note:x[1],status:x[2],category:x[3],group:g,index:i}))) }
function statusText(s){return ({todo:'待准备',packed:'已打包'})[s]}
function groupStatusText(s){return ({todo:'待准备',shipping:'运输中',received:'已收到'})[s]}
function isValidImport(data){return data&&Array.isArray(data.groups)&&data.groups.every(g=>g&&typeof g.id==='string'&&typeof g.name==='string'&&Array.isArray(g.items)&&g.items.every(item=>Array.isArray(item)&&item.length>=3&&typeof item[0]==='string'&&typeof item[1]==='string'&&['todo','packed','shipping','received'].includes(item[2])))&&Array.isArray(data.activity)}
function render(){const all=items(), done=all.filter(x=>x.status==='packed').length, shipping=state.groups.filter(g=>g.status==='shipping').length; $('#tripName').textContent=trip.name; $('#tripMeta').textContent=`${state.groups.length} 个分组 · ${all.length} 件物品`; $('#summaryGrid').innerHTML=[['总物品',all.length,`来自 ${state.groups.length} 个分组`],['已完成',done,`${all.length?Math.round(done/all.length*100):0}% 已准备好`],['运输中',shipping,shipping?'有分组在运输中':'暂无运输中分组'],['待处理',all.length-done,'按分组逐个确认']].map((x,i)=>`<div class="summary-card"><div class="label">${x[0]}</div><div class="value">${x[1]}</div><div class="detail">${i===1?`<em>${x[2]}</em>`:x[2]}</div></div>`).join('');
  const visible=all.filter(x=>(activeFilter==='all'||(activeFilter==='shipping'?x.group.status==='shipping':x.status===activeFilter))&&(activeCategory==='all'||x.category===activeCategory)&&[x.name,x.note,x.group.name].join(' ').toLowerCase().includes(query.toLowerCase())); $('#visibleCount').textContent=`${visible.length} 件物品`; $('#sectionTitle').textContent=activeFilter==='all'?'你的分组':activeFilter==='shipping'?'运输中的分组':statusText(activeFilter); $('#groupList').innerHTML=state.groups.map(g=>{const gi=all.filter(x=>x.group.id===g.id), shown=visible.filter(x=>x.group.id===g.id); const complete=gi.filter(x=>x.status==='packed').length; return `<article class="group-card" draggable="true" data-group-key="${g.id}" title="拖动以排序"><div class="group-top"><div class="group-title-wrap"><span class="group-icon ${g.color}">${g.id==='ship'?'↗':g.id==='move'?'□':g.id==='home'?'⌂':'✦'}</span><div><h3 class="group-title">${g.name}</h3><p class="group-desc">${g.description||'自定义分组'}</p></div></div><div class="group-actions"><select class="group-status-select ${g.status}" data-group-status="${g.id}" aria-label="分组状态">${['todo','shipping','received'].map(s=>`<option value="${s}" ${g.status===s?'selected':''}>${groupStatusText(s)}</option>`).join('')}</select><button class="row-action" data-edit-group="${g.id}" aria-label="编辑分组">✎</button><button class="row-action" data-delete-group="${g.id}" aria-label="删除分组">×</button><span class="progress-label"><strong>${complete}</strong> / ${gi.length}</span></div></div><div class="progress-track"><div class="progress-bar ${complete===gi.length?'complete':''}" style="width:${gi.length?complete/gi.length*100:0}%"></div></div><div class="item-list">${shown.length?shown.map(x=>itemHtml(x)).join(''):'<div class="empty-state">没有符合条件的物品</div>'}</div><button class="add-item-inline" data-group="${g.id}">＋ 添加到这个分组</button></article>`}).join('');
  $('#activityList').innerHTML=state.activity.length?state.activity.map(a=>`<div class="activity"><span class="activity-mark"></span><div><p>${a[0]}</p><time>${a[1]}</time></div></div>`).join(''):'<div class="empty-state">还没有动态</div>'; const now=new Date(); $('#todayText').textContent=[now.getFullYear(),String(now.getMonth()+1).padStart(2,'0'),String(now.getDate()).padStart(2,'0')].join('.');
}
function itemHtml(x){return `<div class="item-row ${x.status==='packed'?'done':''}" draggable="true" data-item-key="${x.group.id}:${x.index}" title="拖动以排序"><span class="drag-handle" aria-hidden="true">⠿</span><button class="check" data-toggle="${x.group.id}:${x.index}" aria-label="切换完成">${x.status==='packed'?'✓':''}</button><span class="item-name">${x.name}</span><span class="item-note">${x.note||''}</span><span class="item-category">${x.category||'其他'}</span><button class="row-action" data-edit-item="${x.group.id}:${x.index}" aria-label="编辑物品">✎</button><button class="row-action item-delete" data-delete-item="${x.group.id}:${x.index}" aria-label="删除物品">×</button></div>`}
function reorderItem(sourceKey,targetKey){if(sourceKey===targetKey)return;const [sourceGroupId,sourceIndex]=sourceKey.split(':'),[targetGroupId,targetIndex]=targetKey.split(':');if(sourceGroupId!==targetGroupId)return;const sourcePosition=Number(sourceIndex),targetPosition=Number(targetIndex);const group=state.groups.find(g=>g.id===sourceGroupId);if(!group)return;const [item]=group.items.splice(sourcePosition,1);group.items.splice(sourcePosition<targetPosition?targetPosition-1:targetPosition,0,item);state.activity.unshift([`调整了「${item[0]}」的顺序`,'刚刚']);state.activity=state.activity.slice(0,5);save()}
function reorderGroup(sourceId,targetId){if(sourceId===targetId)return;const sourcePosition=state.groups.findIndex(g=>g.id===sourceId),targetPosition=state.groups.findIndex(g=>g.id===targetId);if(sourcePosition<0||targetPosition<0)return;const [group]=state.groups.splice(sourcePosition,1);state.groups.splice(sourcePosition<targetPosition?targetPosition-1:targetPosition,0,group);state.activity.unshift([`调整了分组「${group.name}」的顺序`,'刚刚']);state.activity=state.activity.slice(0,5);save()}
function prepareItemModal(key){$('#itemForm').reset();$('#itemForm').dataset.editKey=key||'';$('#itemModalTitle').textContent=key?'编辑物品':'添加物品';$('#itemSaveButton').textContent=key?'保存修改':'保存物品';if(key){const [g,i]=key.split(':'),item=state.groups.find(x=>x.id===g).items[i];$('#itemForm').elements.name.value=item[0];$('#itemForm').elements.group.value=g;$('#itemForm').elements.note.value=item[1]||'';$('#itemForm').elements.category.value=item[3]||categoryForItem(item[0]);$('#itemForm').elements.tracking.value=''}}
function prepareGroupModal(id){$('#groupForm').reset();$('#groupForm').dataset.editId=id||'';$('#groupModalTitle').textContent=id?'编辑分组':'新建分组';if(id){const g=state.groups.find(x=>x.id===id);$('#groupForm').elements.name.value=g.name;$('#groupForm').elements.description.value=g.description||'';$('#groupForm').elements.color.value=g.color}}
function showConfirm(message,title='确认操作'){return new Promise(resolve=>{const backdrop=document.createElement('div');backdrop.className='confirm-backdrop';backdrop.innerHTML='<div class="confirm-dialog" role="dialog" aria-modal="true"><button class="confirm-close" aria-label="关闭">×</button><p class="eyebrow">PLEASE CONFIRM</p><h2></h2><p class="confirm-message"></p><div class="confirm-actions"><button class="secondary-button confirm-cancel">取消</button><button class="primary-button confirm-ok">确认</button></div></div>';backdrop.querySelector('h2').textContent=title;backdrop.querySelector('.confirm-message').textContent=message;const finish=value=>{backdrop.remove();resolve(value)};backdrop.querySelector('.confirm-cancel').addEventListener('click',()=>finish(false));backdrop.querySelector('.confirm-close').addEventListener('click',()=>finish(false));backdrop.querySelector('.confirm-ok').addEventListener('click',()=>finish(true));backdrop.addEventListener('click',e=>{if(e.target===backdrop)finish(false)});document.body.append(backdrop);backdrop.querySelector('.confirm-ok').focus();const onKey=e=>{if(!backdrop.isConnected){document.removeEventListener('keydown',onKey);return}if(e.key==='Escape'){e.preventDefault();finish(false)}};document.addEventListener('keydown',onKey)})}
async function deleteItem(key){const [g,i]=key.split(':'),group=state.groups.find(x=>x.id===g),item=group.items[i];if(!await showConfirm(`确定删除「${item[0]}」吗？`,'删除物品'))return;group.items.splice(i,1);state.activity.unshift([`删除了「${item[0]}」`,'刚刚']);state.activity=state.activity.slice(0,5);save()}
async function deleteGroup(id){const group=state.groups.find(x=>x.id===id);if(!group)return;const suffix=group.items.length?`以及其中的 ${group.items.length} 件物品`:'';if(!await showConfirm(`确定删除分组「${group.name}」${suffix}吗？`,'删除分组'))return;state.groups=state.groups.filter(x=>x.id!==id);state.activity.unshift([`删除了分组「${group.name}」`,'刚刚']);state.activity=state.activity.slice(0,5);save()}
function openModal(id,groupId){$('#'+id).hidden=false;if(groupId)$('#itemGroupSelect').value=groupId} function closeModal(id){$('#'+id).hidden=true}
document.addEventListener('click',e=>{const t=e.target; if(t.matches('[data-close]'))closeModal(t.dataset.close); if(t.id==='tripSwitcher'){ $('#tripForm').elements.name.value=trip.name; openModal('tripModal') } if(t.id==='themeToggle'){applyTheme(document.body.classList.contains('dark')?'light':'dark')} if(t.id==='addItemBtn'){populateGroups();prepareItemModal();openModal('itemModal')} if(t.matches('[data-group]')){populateGroups();prepareItemModal();openModal('itemModal',t.dataset.group)} if(t.id==='addGroupBtn'||t.id==='addGroupRow'){prepareGroupModal();openModal('groupModal')} if(t.matches('[data-edit-group]')){prepareGroupModal(t.dataset.editGroup);openModal('groupModal')} if(t.matches('[data-delete-group]'))deleteGroup(t.dataset.deleteGroup); if(t.matches('[data-edit-item]')){populateGroups();prepareItemModal(t.dataset.editItem);openModal('itemModal')} if(t.matches('[data-delete-item]'))deleteItem(t.dataset.deleteItem); if(t.matches('[data-toggle]')){const [g,i]=t.dataset.toggle.split(':'); const item=state.groups.find(x=>x.id===g).items[i]; item[2]=(item[2]==='packed'?'todo':'packed'); state.activity.unshift([`已将「${item[0]}」标记为${statusText(item[2])}`, '刚刚']);state.activity=state.activity.slice(0,5);save()} if(t.id==='importBtn')$('#importInput').click(); if(t.matches('.nav-item')){const labels={overview:'总览',groups:'所有分组',tracking:'追踪包裹'};$('.nav-item.active').classList.remove('active');t.classList.add('active');$('#pageLabel').textContent=labels[t.dataset.view]; if(t.dataset.view==='tracking'){$('.filter-tab.active').classList.remove('active');$('.filter-tab[data-filter="shipping"]').classList.add('active');activeFilter='shipping'}else{activeFilter='all';document.querySelectorAll('.filter-tab').forEach(x=>x.classList.toggle('active',x.dataset.filter==='all'))} render()} if(t.matches('.filter-tab')){document.querySelector('.filter-tab.active').classList.remove('active');t.classList.add('active');activeFilter=t.dataset.filter;render()} if(t.id==='clearActivity'){state.activity=[];save()} if(t.id==='exportBtn'){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='packflow-list.json';a.click();URL.revokeObjectURL(a.href)}});
document.addEventListener('change',e=>{if(e.target.matches('[data-status]')){const [g,i]=e.target.dataset.status.split(':');state.groups.find(x=>x.id===g).items[i][2]=e.target.value;save()}if(e.target.matches('[data-group-status]')){const group=state.groups.find(x=>x.id===e.target.dataset.groupStatus);if(group){group.status=e.target.value;save()}}}); $('#searchInput').addEventListener('input',e=>{query=e.target.value;render()});
$('#importInput').addEventListener('change',e=>{const file=e.target.files[0];if(!file)return;const reader=new FileReader();reader.onload=async()=>{try{const imported=JSON.parse(reader.result);if(!isValidImport(imported))throw new Error('invalid');if(!await showConfirm(`导入将覆盖当前清单中的 ${state.groups.length} 个分组，确定继续吗？`,'导入数据'))return;state=imported;normalizeState();save();alert('数据导入成功')}catch(error){alert('导入失败：请选择 PackFlow 导出的有效 JSON 文件')}finally{e.target.value=''}};reader.readAsText(file)});
document.addEventListener('dragstart',e=>{const row=e.target.closest('.item-row[draggable]');if(!row)return;if(e.target.closest('button,select')){e.preventDefault();return}draggedItem=row.dataset.itemKey;row.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',draggedItem)});
document.addEventListener('dragover',e=>{const row=e.target.closest('.item-row[draggable]');if(!draggedItem||!row||row.dataset.itemKey.split(':')[0]!==draggedItem.split(':')[0])return;e.preventDefault();e.dataTransfer.dropEffect='move';document.querySelectorAll('.item-row.drag-over').forEach(x=>x.classList.remove('drag-over'));if(row.dataset.itemKey!==draggedItem)row.classList.add('drag-over')});
document.addEventListener('drop',e=>{const row=e.target.closest('.item-row[draggable]');if(!draggedItem||!row||row.dataset.itemKey.split(':')[0]!==draggedItem.split(':')[0])return;e.preventDefault();reorderItem(draggedItem,row.dataset.itemKey);draggedItem=null});
document.addEventListener('dragend',()=>{draggedItem=null;document.querySelectorAll('.item-row.dragging,.item-row.drag-over').forEach(x=>x.classList.remove('dragging','drag-over'))});
document.addEventListener('dragstart',e=>{const card=e.target.closest('.group-card[draggable]');if(!card||e.target.closest('.item-row')||e.target.closest('button,select'))return;draggedGroup=card.dataset.groupKey;card.classList.add('dragging');e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',draggedGroup)});
document.addEventListener('dragover',e=>{const card=e.target.closest('.group-card[draggable]');if(!draggedGroup||!card||card.dataset.groupKey===draggedGroup)return;e.preventDefault();e.dataTransfer.dropEffect='move';document.querySelectorAll('.group-card.drag-over').forEach(x=>x.classList.remove('drag-over'));card.classList.add('drag-over')});
document.addEventListener('drop',e=>{const card=e.target.closest('.group-card[draggable]');if(!draggedGroup||!card||card.dataset.groupKey===draggedGroup)return;e.preventDefault();reorderGroup(draggedGroup,card.dataset.groupKey);draggedGroup=null});
document.addEventListener('dragend',()=>{draggedGroup=null;document.querySelectorAll('.group-card.dragging,.group-card.drag-over').forEach(x=>x.classList.remove('dragging','drag-over'))});
function populateGroups(){$('#itemGroupSelect').innerHTML=state.groups.map(g=>`<option value="${g.id}">${g.name}</option>`).join('')}
function ensureCategoryField(){if($('#itemCategorySelect'))return;const label=document.createElement('label');label.textContent='分类';label.innerHTML=`分类<select name="category" id="itemCategorySelect">${categories.map(category=>`<option value="${category}">${category}</option>`).join('')}</select>`;$('#itemForm').querySelector('label:nth-of-type(2)').after(label)}
ensureCategoryField();
function ensureCategoryFilter(){if($('#categoryFilter'))return;const filter=document.createElement('select');filter.id='categoryFilter';filter.className='category-filter';filter.setAttribute('aria-label','按分类筛选');filter.innerHTML=`<option value="all">全部分类</option>${categories.map(category=>`<option value="${category}">${category}</option>`).join('')}`;$('#searchInput').parentElement.before(filter);filter.addEventListener('change',e=>{activeCategory=e.target.value;render()})}
ensureCategoryFilter();
$('#itemForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),key=e.target.dataset.editKey,g=state.groups.find(x=>x.id===f.get('group')),note=f.get('tracking')||f.get('note')||'',category=f.get('category')||'其他';if(key){const [oldGroup,idx]=key.split(':'),item=state.groups.find(x=>x.id===oldGroup).items[idx],oldStatus=item[2];if(oldGroup===g.id){item[0]=f.get('name');item[1]=note;item[2]=oldStatus;item[3]=category}else{g.items.push([f.get('name'),note,oldStatus,category]);state.groups.find(x=>x.id===oldGroup).items.splice(idx,1)}state.activity.unshift([`修改了「${f.get('name')}」`,'刚刚'])}else{if(f.get('tracking'))g.status='shipping';g.items.push([f.get('name'),note,'todo',category]);state.activity.unshift([`新增「${f.get('name')}」到${g.name}`,'刚刚'])}state.activity=state.activity.slice(0,5);closeModal('itemModal');save()});
$('#groupForm').addEventListener('submit',e=>{e.preventDefault();const f=new FormData(e.target),id=e.target.dataset.editId;if(id){const g=state.groups.find(x=>x.id===id);g.name=f.get('name');g.description=f.get('description');g.color=f.get('color');state.activity.unshift([`修改了分组「${g.name}」`,'刚刚'])}else{const newId='g'+Date.now();state.groups.push({id:newId,name:f.get('name'),description:f.get('description'),color:f.get('color'),status:'todo',items:[]});state.activity.unshift([`创建分组「${f.get('name')}」`,'刚刚'])}state.activity=state.activity.slice(0,5);closeModal('groupModal');save()});
$('#tripForm').addEventListener('submit',e=>{e.preventDefault();const name=new FormData(e.target).get('name').trim();if(!name)return;trip={name};localStorage.setItem('packflow-trip',JSON.stringify(trip));closeModal('tripModal');render()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')document.querySelectorAll('.modal-backdrop:not([hidden])').forEach(x=>closeModal(x.id)); if(e.target.id==='tripSwitcher'&&(e.key==='Enter'||e.key===' ')){e.preventDefault();$('#tripForm').elements.name.value=trip.name;openModal('tripModal')} if((e.metaKey||e.ctrlKey)&&e.key.toLowerCase()==='k'){e.preventDefault();$('#searchInput').focus()}});
$('#themeToggle').addEventListener('click',e=>{e.stopPropagation();applyTheme(document.body.classList.contains('dark')?'light':'dark')});
applyTheme(preferredTheme); render();
